window['createExportImageApi']=()=>{const exportImageApi={};const exportVideoApi=window['createExportVideoApi']();const export3DVideoApi=window['createExport3DVideoApi']();let have3DCharacter=false;exportImageApi['prepareCapturing']=(svgContent,pageWidth,pageHeight,videoWidth,videoHeight)=>{return new Promise((resolve,reject)=>{try{exportVideoApi['prepareCapturing'](svgContent,pageWidth,pageHeight,videoWidth,videoHeight).then((values)=>{try{const svgElement=values['svgElement'];const threeDCharacters=svgElement.querySelectorAll('character-3d');have3DCharacter=threeDCharacters.length>0;if(!have3DCharacter){resolve(true);return;}
const getShapeNode=(threeDCharacter=>{return threeDCharacter.closest('g[shape-node]');});const first3DShapeNode=getShapeNode(threeDCharacters[0]);const containerGNode=document.createElementNS('http://www.w3.org/2000/svg','g');containerGNode.style.transformOrigin='0 0';first3DShapeNode.parentNode.insertBefore(containerGNode,first3DShapeNode);const innerContainerGNode=document.createElementNS('http://www.w3.org/2000/svg','g');containerGNode.appendChild(innerContainerGNode);const foreignObjectNode=document.createElementNS('http://www.w3.org/2000/svg','foreignObject');foreignObjectNode.setAttribute('ignore-fo-fix','true');foreignObjectNode.setAttribute('width',pageWidth);foreignObjectNode.setAttribute('height',pageHeight);innerContainerGNode.appendChild(foreignObjectNode);containerGNode.style.transform=`scale(${pageWidth/videoWidth})`;const svgNode=document.createElementNS('http://www.w3.org/2000/svg','svg');svgNode.setAttribute('s-c','');svgNode.setAttribute('id','3d-svg-root');foreignObjectNode.appendChild(svgNode);const gNode=document.createElementNS('http://www.w3.org/2000/svg','g');gNode.setAttribute('graphViewDrawPane','true');svgNode.appendChild(gNode);Array.from(threeDCharacters).map(threeDCharacter=>{const shapeNode=getShapeNode(threeDCharacter);shapeNode.remove();});const waitForJs=window['vpCommonApi']['waitForJs'];waitForJs('character-3d.js').finally(()=>{try{const animationData=JSON.parse(svgElement.getAttribute('animation'));const threeDAnimationData=JSON.parse(svgElement.getAttribute('threeDAnimation')||svgElement.getAttribute('threedanimation'));const data={...animationData,...threeDAnimationData};export3DVideoApi['prepareCapturing'](data,pageWidth,pageHeight).then((result)=>{containerGNode.style.transform='scale(1)';const clipElement=document.querySelector('#ani-api-clip');clipElement.style.width=`${videoWidth}px`;clipElement.style.height=`${videoHeight}px`;resolve(result);}).catch(reject);}catch(error){reject(error);}});}catch(error){reject(error);}}).catch(reject);}catch(error){reject(error);}});};exportImageApi['startCapturing']=()=>{return new Promise((resolve,reject)=>{exportVideoApi['startCapturing']().then(()=>{try{if(!have3DCharacter){resolve(true);return;}
export3DVideoApi['startCapturing']().then(resolve).catch(reject);}catch(error){reject(error);}}).catch(reject);});};exportImageApi['isCapturing']=()=>{if(!exportVideoApi['isCapturing']()){return false;}
if(!have3DCharacter){return true;}
return export3DVideoApi['isCapturing']();};exportImageApi['resetSeekCount']=()=>{exportVideoApi['resetSeekCount']();if(!have3DCharacter){return;}
export3DVideoApi['resetSeekCount']();};exportImageApi['waitForSeekCount']=()=>{return new Promise((resolve,reject)=>{exportVideoApi['waitForSeekCount']().then(()=>{try{if(!have3DCharacter){resolve(true);return;}
export3DVideoApi['waitForSeekCount']().then(resolve).catch(reject);}catch(error){reject(error);}}).catch(reject);});};exportImageApi['increaseSeekCount']=()=>{exportVideoApi['increaseSeekCount']();if(!have3DCharacter){return;}
export3DVideoApi['increaseSeekCount']();};exportImageApi['decreaseSeekCount']=()=>{exportVideoApi['decreaseSeekCount']();if(!have3DCharacter){return;}
export3DVideoApi['decreaseSeekCount']();};exportImageApi['seekTo']=(time)=>{return new Promise((resolve,reject)=>{exportVideoApi['seekTo'](time).then(()=>{try{if(!have3DCharacter){resolve(true);return;}
export3DVideoApi['seekTo'](time).then(resolve).catch(reject);}catch(error){reject(error);}}).catch(reject);});};exportImageApi['dispose']=()=>{return export3DVideoApi['dispose']();};return exportImageApi;};