(()=>{const ensureVersion=(svg)=>{let version=svg.getAttribute('flipbook-version');if(!version){version=(()=>{let svgAnimations=svg.getAttribute('animation');if(svgAnimations){svgAnimations=JSON.parse(svgAnimations);}
if(!svgAnimations){return null;}
const meta=svgAnimations['meta'];if(!meta){return null;}
return meta['version'];})();if(!version){version='LEGACY';}else{version=''+version;}
svg.setAttribute('flipbook-version',version);}
return version;};const ensureInstanceId=(svg)=>{if(typeof(svg)=='string'){return svg;}
let _INSTANCE_ID=svg.getAttribute('flipbook-instance-id');if(!_INSTANCE_ID){_INSTANCE_ID='SHARED';svg.setAttribute('flipbook-instance-id',_INSTANCE_ID);}
return _INSTANCE_ID;};const ensureKey=(object,key,defaultValue)=>{let value=object[key];if(value==null){value=defaultValue;object[key]=value;}
return value;};const ensureFlipbookStorage=()=>{const flipbookStorage=ensureKey(window,'flipbookStorage',{});ensureKey(flipbookStorage,'flipbookApi.js',{});return flipbookStorage;};const ensureInstanceStorage=(_INSTANCE_ID)=>{const flipbookStorage=ensureFlipbookStorage();const instanceStorages=flipbookStorage['flipbookApi.js'];const instanceStorage=ensureKey(instanceStorages,_INSTANCE_ID,{});ensureKey(instanceStorage,'pageStorages',{});return instanceStorage;};const disposeInstanceStorage=(_INSTANCE_ID)=>{const flipbookStorage=ensureFlipbookStorage();const instanceStorages=flipbookStorage['flipbookApi.js'];delete instanceStorages[_INSTANCE_ID];};const ensurePageStorage=(_INSTANCE_ID,pageNumber)=>{const instanceStorage=ensureInstanceStorage(_INSTANCE_ID);const pageStorages=instanceStorage['pageStorages'];return ensureKey(pageStorages,pageNumber,{});};const disposePageStorage=(_INSTANCE_ID,pageNumber)=>{const instanceStorage=ensureInstanceStorage(_INSTANCE_ID);const pageStorages=instanceStorage['pageStorages'];delete pageStorages[pageNumber];};const setValue=(svg,pageNumber,key,value)=>{const _INSTANCE_ID=ensureInstanceId(svg);const pageStorage=ensurePageStorage(_INSTANCE_ID,pageNumber);pageStorage[key]=value;};const getValue=(svg,pageNumber,key)=>{const _INSTANCE_ID=ensureInstanceId(svg);const pageStorage=ensurePageStorage(_INSTANCE_ID,pageNumber);return pageStorage[key];};window['createFlipbookApi']=async()=>{await window['ensureLoadedFlipbookJs']();const flipbookApi={};flipbookApi['initAnimation']=(svg,pageNumber,options)=>{const version=ensureVersion(svg);if(version=='LEGACY'){return window['initAnimation'](svg,pageNumber,options);}else if(version=='20230504'){return new Promise((resolve,reject)=>{window['initAnimation'](svg,pageNumber,options).then(()=>{try{((svgElement)=>{const md5=window['md5'];if(md5!=null){const images=Array.from(svgElement.querySelectorAll('image[pointer-events=none]'));if(images.length>=1){const image=images[images.length-1];if(['43e8298716fef7a7219e1643f5fc101a','44cff975acb83aa941437d8762dc9e78'].includes(md5(image.getAttribute('xlink:href')))){window['flipbookAnimation_20230504']['utils']['compensateSvgCameraWithObserve'](svgElement,image);}}}})(svg);const svgElement=svg;const pageMeta=JSON.parse(svgElement.getAttribute('animation'))['pageMeta'];const pageWidth=pageMeta['page_width'];const pageHeight=pageMeta['page_height'];const threeDCharacters=svgElement.querySelectorAll('character-3d');const have3DCharacter=threeDCharacters.length>0;setValue(svg,pageNumber,'have3DCharacter',have3DCharacter);if(!have3DCharacter){resolve(true);return;}
svgElement.setAttribute('free-from-container','true');const rollbackAll=[];rollbackAll.push(()=>svgElement.removeAttribute('free-from-container'));const export3DVideoApi=window['createExport3DVideoApi']();setValue(svg,pageNumber,'export3DVideoApi',export3DVideoApi);const getShapeNode=(threeDCharacter=>{return threeDCharacter.closest('g[shape-node]');});const first3DShapeNode=getShapeNode(threeDCharacters[0]);const containerGNode=document.createElementNS('http://www.w3.org/2000/svg','g');containerGNode.style.transformOrigin='0 0';first3DShapeNode.parentNode.insertBefore(containerGNode,first3DShapeNode);const innerContainerGNode=document.createElementNS('http://www.w3.org/2000/svg','g');containerGNode.appendChild(innerContainerGNode);const foreignObjectNode=document.createElementNS('http://www.w3.org/2000/svg','foreignObject');foreignObjectNode.setAttribute('ignore-fo-fix','true');foreignObjectNode.setAttribute('width',pageWidth);foreignObjectNode.setAttribute('height',pageHeight);innerContainerGNode.appendChild(foreignObjectNode);const svgNode=document.createElementNS('http://www.w3.org/2000/svg','svg');svgNode.setAttribute('s-c','');svgNode.setAttribute('id','3d-svg-root');foreignObjectNode.appendChild(svgNode);const gNode=document.createElementNS('http://www.w3.org/2000/svg','g');gNode.setAttribute('graphViewDrawPane','true');if(options!=null&&options['useContextPool']!=null&&options['useContextPool']){gNode.setAttribute('useContextPool','true');}
svgNode.appendChild(gNode);Array.from(threeDCharacters).map(threeDCharacter=>{const newThreeDCharacterNode=document.createElement('character-3d-deprecated');threeDCharacter.getAttributeNames().map((attributeName)=>{newThreeDCharacterNode.setAttribute(attributeName,threeDCharacter.getAttribute(attributeName));});threeDCharacter.parentNode.insertBefore(newThreeDCharacterNode,threeDCharacter);threeDCharacter.remove();});const waitForJs=window['vpCommonApi']['waitForJs'];waitForJs('character-3d.js').finally(()=>{try{const animationData=JSON.parse(svgElement.getAttribute('animation'));const threeDAnimationData=JSON.parse(svgElement.getAttribute('threeDAnimation')||svgElement.getAttribute('threedanimation'));const data={...animationData,...threeDAnimationData};export3DVideoApi['setupForFlipbookApi']({'pageNumber':pageNumber,'svgNode':svgNode,'gNode':gNode});export3DVideoApi['prepareCapturing'](data,pageWidth,pageHeight,options).then((result)=>{rollbackAll.forEach(rollback=>rollback());resolve(result);}).catch(reject);}catch(error){reject(error);}});}catch(error){reject(error);}}).catch(reject);});}else{return Promise.resolve(true);}};flipbookApi['getAnimationMeta']=(svg,pageNumber)=>{return window['getAnimationMeta'](svg,pageNumber);};flipbookApi['getAnimationFrameMeta']=(svg,pageNumber)=>{const export3DVideoApi=getValue(svg,pageNumber,'export3DVideoApi');if(!export3DVideoApi){return Promise.resolve(null);}
return new Promise((resolve,reject)=>{try{const cellLocations={};const frameMeta={'cellLocations':cellLocations};const threeDCharacters=svg.querySelectorAll('character-3d');Array.from(threeDCharacters).map(threeDCharacter=>{const cellId=threeDCharacter.getAttribute('cell-id');const bounds=JSON.parse(threeDCharacter.getAttribute('data-char-bounds'))
const api=threeDCharacter['api'];const characterBounds=api['getCharacterBounds']();const x=bounds['x'];const y=bounds['y'];const width=bounds['width'];const height=bounds['height'];const centerX=x+(width/2);const centerY=y+(height/2);const characterX=characterBounds['x'];const characterY=characterBounds['y'];const characterWidth=characterBounds['width'];const characterHeight=characterBounds['height'];const characterCenterX=characterX+(characterWidth/2);const characterCenterY=characterY+(characterHeight/2);const xDiff=characterCenterX-centerX;const yDiff=characterCenterY-centerY;cellLocations[cellId]={'x':x+xDiff,'y':y+yDiff};});resolve(frameMeta);}catch(error){reject(error);}});};flipbookApi['seekAnimationTo']=(svg,pageNumber,time)=>{const version=ensureVersion(svg);if(version=='LEGACY'){return window['seekAnimationTo'](svg,pageNumber,time);}else if(version=='20230504'){return new Promise((resolve,reject)=>{try{window['seekAnimationTo'](svg,pageNumber,time).then(()=>{const have3DCharacter=getValue(svg,pageNumber,'have3DCharacter');if(!have3DCharacter){resolve(true);return;}
const export3DVideoApi=getValue(svg,pageNumber,'export3DVideoApi');if(!export3DVideoApi){resolve(true);return;}
export3DVideoApi['seekTo'](time).then(resolve).catch(reject);}).catch(reject);}catch(error){reject(error);}});}else{return Promise.resolve(true);}};flipbookApi['preStartAnimation']=(svg,pageNumber)=>{const version=ensureVersion(svg);if(version=='LEGACY'){return window['preStartAnimation'](svg,pageNumber);}else if(version=='20230504'){return new Promise((resolve,reject)=>{try{window['preStartAnimation'](svg,pageNumber).then(()=>{const have3DCharacter=getValue(svg,pageNumber,'have3DCharacter');if(!have3DCharacter){resolve(true);return;}
const export3DVideoApi=getValue(svg,pageNumber,'export3DVideoApi');if(!export3DVideoApi){resolve(true);return;}
export3DVideoApi['pause'](0).then(resolve).catch(reject);}).catch(reject);}catch(error){reject(error);}});}else{return Promise.resolve(true);}};flipbookApi['animate']=(svg,pageLayout,pageNumber)=>{const version=ensureVersion(svg);if(version=='LEGACY'){return window['animate'](svg,pageLayout,pageNumber);}else if(version=='20230504'){return new Promise((resolve,reject)=>{try{window['animate'](svg,pageLayout,pageNumber).then(()=>{const have3DCharacter=getValue(svg,pageNumber,'have3DCharacter');if(!have3DCharacter){resolve(true);return;}
const export3DVideoApi=getValue(svg,pageNumber,'export3DVideoApi');if(!export3DVideoApi){resolve(true);return;}
let rollback=()=>{};const startAnimateImpl=()=>{export3DVideoApi['play'](null).then(()=>{rollback();resolve(true);}).catch(reject);};let delay=false;if(pageLayout=='double'&&pageNumber!=null){let isStartAnimationWithPreviousPage=svg.getAttribute('isstartanimationwithpreviouspage');if(isStartAnimationWithPreviousPage==null){isStartAnimationWithPreviousPage=svg.getAttribute('isStartAnimationWithPreviousPage');}
if(pageNumber==1){isStartAnimationWithPreviousPage='with';}else if(pageNumber%2==0){isStartAnimationWithPreviousPage='with';}
if(isStartAnimationWithPreviousPage=='after'){delay=true;}}
const previousPageNumber=pageNumber-1;if(previousPageNumber>0&&svg['no_interaction']!=true){const _INSTANCE_ID=ensureInstanceId(svg);window['flipbookAnimation_20230504']['utils']['getTimelineWithoutCreate'](_INSTANCE_ID,previousPageNumber).then(previousTimeline=>{if(previousTimeline['totalDuration']()==0){startAnimateImpl(pageNumber);}else if(delay){const observer={'end':()=>{startAnimateImpl();}};rollback=()=>{previousTimeline['removeObserver'](observer);};previousTimeline['addObserver'](observer);}});}
if(delay){resolve(true);}else{startAnimateImpl();}}).catch(reject);}catch(error){reject(error);}});}else{return Promise.resolve(true);}};flipbookApi['endAnimation']=(svg,pageNumber,time=0)=>{const version=ensureVersion(svg);if(version=='LEGACY'){return window['endAnimation'](svg,pageNumber,time);}else if(version=='20230504'){return new Promise((resolve,reject)=>{try{window['endAnimation'](svg,pageNumber,time).then(()=>{const have3DCharacter=getValue(svg,pageNumber,'have3DCharacter');if(!have3DCharacter){resolve(true);return;}
const export3DVideoApi=getValue(svg,pageNumber,'export3DVideoApi');if(!export3DVideoApi){resolve(true);return;}
export3DVideoApi['pause'](time).then(resolve).catch(reject);}).catch(reject);}catch(error){reject(error);}});}else{return Promise.resolve(true);}};flipbookApi['disposeAnimation']=(svg,pageNumber)=>{const promise=(()=>{const version=ensureVersion(svg);if(version=='LEGACY'){return window['disposeAnimation'](svg,pageNumber);}else if(version=='20230504'){return new Promise((resolve,reject)=>{try{window['disposeAnimation'](svg,pageNumber).then(()=>{const have3DCharacter=getValue(svg,pageNumber,'have3DCharacter');if(!have3DCharacter){resolve(true);return;}
const export3DVideoApi=getValue(svg,pageNumber,'export3DVideoApi');if(!export3DVideoApi){resolve(true);return;}
export3DVideoApi['dispose']().then(resolve).catch(reject);}).catch(reject);}catch(error){reject(error);}});}else{return Promise.resolve(true);}})();return new Promise((resolve,reject)=>{promise.then(()=>{try{const _INSTANCE_ID=ensureInstanceId(svg);disposePageStorage(_INSTANCE_ID,pageNumber);resolve(true);}catch(error){reject(error);}}).catch(reject);});};flipbookApi['resetAnimationVersion']=(_INSTANCE_ID)=>{window['resetAnimationVersion'](_INSTANCE_ID);disposeInstanceStorage(_INSTANCE_ID);};return flipbookApi;};})();